language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.0.5
os:
  - linux
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - >
    dnu restore
    dnx test